In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import datetime

c:\Users\riven\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\riven\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\riven\anaconda3\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df = pd.read_csv("Predict_ready_df")

# Transform cyclic features

In [3]:
from sklearn.preprocessing import FunctionTransformer

def sin_transformer(period):
    return FunctionTransformer(lambda x: np.sin(x / period * 2 * np.pi))


def cos_transformer(period):
    return FunctionTransformer(lambda x: np.cos(x / period * 2 * np.pi))

hour_arr = np.array(df['hour'])
day_arr = np.array(df['day_of_week'])

df['hour_sin'] = sin_transformer(24).fit_transform(hour_arr.reshape(-1,1))
df['hour_cos'] = cos_transformer(24).fit_transform(hour_arr.reshape(-1,1))
df['day_of_week_sin'] = sin_transformer(24).fit_transform(day_arr.reshape(-1,1))
df['day_of_week_cos'] = cos_transformer(24).fit_transform(day_arr.reshape(-1,1))

In [4]:
df

Unnamed: 0            timestamp  station_id  bike_id    idle_time  \
0                 0  2019-01-01 01:00:00           3     5426     0.000000   
1                 1  2019-01-01 09:00:00           3     2191   113.283333   
2                 2  2019-01-01 09:00:00           3     5063   107.800000   
3                 3  2019-01-01 09:00:00           3     5262    98.400000   
4                 4  2019-01-01 10:00:00           3     5354    31.116667   
...             ...                  ...         ...      ...          ...   
3132766     3132766  2019-12-23 17:00:00         498   353685   975.483333   
3132767     3132767  2019-12-24 10:00:00         498    10310   196.016667   
3132768     3132768  2019-12-30 14:00:00         498    10962     0.383333   
3132769     3132769  2019-12-30 14:00:00         498    10962  1252.866667   
3132770     3132770  2019-12-31 12:00:00         498    10962     0.000000   

         temperature  rain  hour  day_of_week       lat        lon  \
0               12.0     0     1            1  37.78638 -122.40490   
1               10.0     0     9            1  37.78638 -122.40490   
2               10.0     0     9            1  37.78638 -122.40490   
3               10.0     0     9            1  37.78638 -122.40490   
4                9.0     0    10            1  37.78638 -122.40490   
...              ...   ...   ...          ...       ...        ...   
3132766         10.0     0    17            0  37.72589 -122.45244   
3132767          8.0     0    10            1  37.72589 -122.45244   
3132768          9.0     0    14            0  37.72589 -122.45244   
3132769          9.0     0    14            0  37.72589 -122.45244   
3132770          5.0     0    12            1  37.72589 -122.45244   

         near_bus_station  near_school  near_leisure_spots      hour_sin  \
0                       0            0                   1  2.588190e-01   
1                       0            0                   1  7.071068e-01   
2                       0            0                   1  7.071068e-01   
3                       0            0                   1  7.071068e-01   
4                       0            0                   1  5.000000e-01   
...                   ...          ...                 ...           ...   
3132766                 0            1                   1 -9.659258e-01   
3132767                 0            1                   1  5.000000e-01   
3132768                 0            1                   1 -5.000000e-01   
3132769                 0            1                   1 -5.000000e-01   
3132770                 0            1                   1  1.224647e-16   

         hour_cos  day_of_week_sin  day_of_week_cos  
0        0.965926         0.258819         0.965926  
1       -0.707107         0.258819         0.965926  
2       -0.707107         0.258819         0.965926  
3       -0.707107         0.258819         0.965926  
4       -0.866025         0.258819         0.965926  
...           ...              ...              ...  
3132766 -0.258819         0.000000         1.000000  
3132767 -0.866025         0.258819         0.965926  
3132768 -0.866025         0.000000         1.000000  
3132769 -0.866025         0.000000         1.000000  
3132770 -1.000000         0.258819         0.965926  

[3132771 rows x 18 columns]

In [24]:
xp = df[['temperature','rain','hour_sin','hour_cos','near_bus_station','near_school','near_leisure_spots',
         'day_of_week_sin','day_of_week_cos']].values



yp= df['idle_time'].values

In [25]:
X_train_val, X_test, y_train_val, y_test = train_test_split(xp, yp, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.1765, random_state=42)

Scaling features

In [29]:
X_train

array([[23.        ,  0.        , -0.25881905, ...,  1.        ,
         0.5       ,  0.8660254 ],
       [17.        ,  0.        , -0.25881905, ...,  1.        ,
         0.        ,  1.        ],
       [22.        ,  0.        , -0.96592583, ...,  1.        ,
         0.96592583,  0.25881905],
       ...,
       [11.        ,  0.        ,  0.25881905, ...,  1.        ,
         0.        ,  1.        ],
       [ 8.        ,  0.        , -0.96592583, ...,  1.        ,
         0.5       ,  0.8660254 ],
       [10.        ,  1.        ,  0.5       , ...,  1.        ,
         0.5       ,  0.8660254 ]])

In [49]:
from sklearn.preprocessing import PolynomialFeatures
degree = 5
poly = PolynomialFeatures(degree= degree,include_bias= False)
poly_x = poly.fit_transform(X_train.reshape(-1,1))
poly_test = poly.transform(X_test.reshape(-1,1))


In [50]:


from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(poly_x)



StandardScaler()

In [62]:
variable_index = 0  # Index of the variable to rescale

poly_x_train_scaled= scaler.transform(poly_x)
poly_test_scaled= scaler.transform(poly_test)


In [65]:
len(poly_x_train_scaled)

2192861

In [64]:
poly_x_train_scaled = poly_x_train_scaled.reshape(-1,45)

In [66]:
scaler_y = StandardScaler()

In [67]:

y_train_reshape = np.reshape(y_train,(-1,1))
y_test_reshape = np.reshape(y_test,(-1,1))
scaler_y.fit(y_train_reshape)


StandardScaler()

In [68]:
y_train_scaled = scaler_y.transform(y_train_reshape)
y_test_scale=scaler_y.transform(y_test_reshape)


In [34]:
len(y_train_scaled)

2192861

In [35]:
# let's fit the model



# we use linear regression as a base!!! ** sometimes misunderstood **
regression_model = LinearRegression()

regression_model.fit(poly_x_train_scaled, y_train_scaled)
print(regression_model.coef_ ,regression_model.intercept_)
regression_model.coef_
regression_model.intercept_







[[-3.87462550e-02  3.57024390e-02 -1.40155848e-02  6.87440233e+08
  -1.28303626e+10  9.05015354e+09 -1.64558466e-02  1.09662017e+11
  -3.21216328e+01  1.14847291e+00  1.09662017e+11  7.84242072e+01
   9.35527158e+07 -2.10547343e+09  8.66154192e+09 -2.93227956e+08
   4.84943983e+09  9.02609066e+09 -6.59187127e+09  1.18133202e+11
   1.44575038e+10 -7.53126784e-01 -4.75074790e+06 -1.99208493e+03
   8.53128951e-01 -4.75100024e+06  2.53546959e+03]] [1.05722803e+11]


array([1.05722803e+11])

In [69]:
from sklearn.linear_model import Ridge

# initialize model
model_L2 = Ridge(alpha = 0.01, solver = 'lsqr') # select least squares regression as solver

# train model
model_L2.fit(poly_x_train_scaled, y_train_scaled)


print("Coefficients ", model_L2.coef_, "\nIntercept ", model_L2.intercept_ )

Coefficients  [[-1.07686706e-02 -9.67144021e-03 -2.81108914e-03  5.91377571e-03
   8.04956632e-03  2.77434498e-03 -4.04323683e-03 -6.68598099e-03
  -2.88252430e-03  6.63737208e-03  1.77828211e-01  9.86447404e-03
   4.77175527e-04  2.03819211e-05  7.82999478e-07  2.76785401e-08
   9.20852529e-10  2.93665629e-11  9.09388384e-13  2.75817794e-14
  -1.09215355e-02 -1.32533545e-01  1.21112058e-03 -2.88571606e-04
   2.86410816e-06 -3.77385783e-07  3.90115677e-09 -3.79753052e-10
   4.14044378e-12 -3.37914791e-13  9.46841999e-01  1.32533545e-01
  -1.60226727e-05  2.59108533e-04 -9.66499349e-07  3.17369740e-07
  -1.46139659e-09  3.05394317e-10 -1.53454260e-12  2.63005070e-13
  -4.35478028e-01 -2.41568066e-02 -1.16854045e-03 -4.99126587e-05
  -1.91746330e-06 -6.77811242e-08 -2.25504739e-09 -7.19148711e-11
  -2.22697320e-12 -6.75441731e-14  7.24384007e-01  4.01829788e-02
   1.94377663e-03  8.30258462e-05  3.18955185e-06  1.12748656e-07
   3.75109687e-09  1.19624824e-10  3.70439763e-12  1.12354504e

In [47]:
from sklearn.linear_model import Lasso

model_L1 = Lasso(alpha = 0.001)

model_L1.fit(poly_x_train_scaled, y_train_scaled)


print("Coefficients ", model_L1.coef_, "\nIntercept ", model_L1.intercept_ )

Coefficients  [-0.0200706  -0.          0.00565451  0.          0.          0.
 -0.         -0.          0.          0.87372982  0.         -0.
 -0.2388903  -0.         -0.          0.35499969  0.          0.
 -0.25366946 -0.         -0.          0.          0.          0.
 -0.27357024 -0.         -0.        ] 
Intercept  [0.37545148]


In [57]:
poly.transform(X_test)

array([[-4.21583255,  0.        , -0.70710678, ...,  0.9330127 ,
         0.25      ,  0.0669873 ],
       [-4.24240382,  0.        , -0.8660254 , ...,  0.0669873 ,
         0.25      ,  0.9330127 ],
       [-4.30883199,  1.        ,  0.5       , ...,  0.25      ,
         0.4330127 ,  0.75      ],
       ...,
       [-4.12283312,  0.        , -0.8660254 , ...,  0.25      ,
         0.4330127 ,  0.75      ],
       [-4.17597565,  0.        , -0.96592583, ...,  0.        ,
         0.        ,  1.        ],
       [-4.33540326,  0.        ,  0.5       , ...,  0.        ,
         0.        ,  1.        ]])

In [71]:

train_pred = model_L2.predict(poly_x_train_scaled)
print("Test set performance:")

print("MAE:",mean_absolute_error(y_train_scaled, train_pred))
print("RMSE:",(mean_squared_error(y_train_scaled, train_pred))**(0.5))  
print("R2:",r2_score(y_train_scaled, train_pred))

Test set performance:
MAE: 0.22003784322352893
RMSE: 0.9925188368243195
R2: 0.014906358548899878


In [20]:
from sklearn.neighbors import KNeighborsRegressor

# initialize
KNN_reg = KNeighborsRegressor(n_neighbors=50) # specify the number of neighbors you want to use

# train
KNN_model = KNN_reg.fit(X_train, y_train) 

# predict
y_hat_KNN = KNN_model.predict(X_test)

ValueError: Expected 2D array, got 1D array instead:
array=[-0.10182379 -0.49637381  4.0603295  ... -0.49637381 -0.29825627
 -0.10013874].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [8]:
print("Test set performance:")

print("MAE:",mean_absolute_error(y_test, y_hat_KNN), "GW")
print("RMSE:",(mean_squared_error(y_test, y_hat_KNN))**(0.5), "GW")  
print("R2:",r2_score(y_test, y_hat_KNN))

Test set performance:
MAE: 182.4126104601674 GW
RMSE: 437.91644315195015 GW
R2: -0.057951284211713805
